name: flutter_mobience
description: Flutter Mobience SDK plugin
version: 1.0.0
homepage: https://wiki.spicymobile.pl/wiki/mobigatesdk


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pl.spicymobile.flutter_mobience
        pluginClass: FlutterMobiencePlugin